networks:
  default:
    driver: bridge
    name: roboshop
    external: false

services:
  mongodb:
    image: kishore8856/mongodb:v1
    container_name: mongodb

  catalogue:
    image: kishore8856/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
    




